services:
    oxpus.dl_ext.controller:
        class: oxpus\dl_ext\controller\main
        arguments:
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
            - @service_container
            - @ext.manager
            - @path_helper
            - @dbal.conn
            - @config
            - @log
            - @controller.helper
            - @auth
            - @request
            - @template
            - @user
    oxpus.dl_ext.listener:
        class: oxpus\dl_ext\event\main_listener
        arguments:
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
            - @ext.manager
            - @path_helper
            - @service_container
            - @dbal.conn
            - @config
            - @controller.helper
            - @auth
            - @template
            - @user
        tags:
            - { name: event.listener }
